[project]
name = "pyvot"
version = "0.1.0"
requires-python = ">=3.13"
description = ""
authors = ["Jan Burgy <jburgy@gmail.com>"]
readme = "README.md"
dependencies = [
    "fastapi>=0.115.12",
    "jinja2>=3.1.6",
    "uvicorn>=0.34.3",
]

[dependency-groups]
dev = [
    "mypy>=1.16.1",
]
